### ISSUE TITLE
1.12.2 Gifs play in slow-motion

### ISSUE THREAD

**Issue by ghost** [CreeperHost/BlockShot#4]
https://blockshot.ch/dqsJ example

The high RAM useage is gone, but the gifs unfortunately play back as if in slow-motion. Could it be a framerate thing?

**Comment by ThePaul-T** [comment]
First second or so does seem a little off, but that is likely because we're counting the frames ourselves as the built-in fps counter seemed to give wildly inaccurate results in testing, so the first second may not have the correct amount of images (10) embedded.

Unfortunately, that is likely a long-term trade-off you'll see in 1.12, that issue does not exist in later Minecraft versions.

After the first second, your gif appears to play at expected speed.

**Comment by gigabit101** [comment]
I belave we backported the fix for this to 1.12? Feel free to re-open if the issue continues
